name: Cron CI

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  load_tests:
    name: Run load tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install Locust
      run: python3 -m pip install locust
    - name: Run Load tests
      run: locust --config=loadtests/config/test.conf