# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Master CICD

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build native application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build native with Maven
      run: mvn -B package -Pnative -Dquarkus.native.container-build=true
    - name: Upload target for next job
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target

  quality_analysis:
    name: Sonar code analysis
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Verify Sonar with maven
      run: mvn verify sonar:sonar

  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Download target from previous job
      uses: actions/download-artifact@v1
      with:
        name: target
    - name: Login into Heroku
      uses: actions/heroku@master
      with:
        args: container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Build and Push to Heroku Registry
      uses: actions/heroku@master
      with:
        args: container:push web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Trigger release in Heroku
      uses: actions/heroku@master
      with:
        args: container:release web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}

  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: [build, deploy_to_heroku]
    steps:
    - uses: actions/checkout@v2
    - uses: matt-ball/newman-action@master
      with:
        collection: integrationtests/quarkus-github-flow.postman_collection.json
        environment: integrationtests/env/quarkus-github-flow-heroku.postman_environment.json